import mongoose from "mongoose";

const subscriptionSchema = new mongoose.Schema(
	{
		userId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
			required: true,
			index: true,
		},
		planId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "Plan",
			required: true,
		},

		razorpaySubscriptionId: {
			type: String,
			required: true,
			unique: true,
		},
		status: {
			type: String,

			enum: [
				"created", // Initial state when generated by your backend
				"authenticated", // User successfully added card, waiting for first charge
				"active", // Charging successfully
				"pending", // Charge failed, will retry
				"halted", // Retries exhausted
				"cancelled", // User or admin cancelled
				"completed", // All billing cycles finished
				"expired", // Link expired before user paid
			],
			required: true,
			default: "created",
		},
		currentPeriodEnd: {
			type: Date,
		},
		cancelAtPeriodEnd: {
			type: Boolean,
			default: false,
		},
	},
	{ timestamps: true }
);

subscriptionSchema.methods.isValid = function () {
	return (
		this.status === "active" && new Date(this.currentPeriodEnd) > new Date()
	);
};

const Subscription = mongoose.model("Subscription", subscriptionSchema);
export default Subscription;
